services:
  core:
    build:
      context: .
      dockerfile: docker/core.Dockerfile
    image: ghcr.io/raolivei/ollie-core
    environment:
      - WHISPER_URL=http://whisper:8000
      - OLLAMA_URL=http://ollama:11434
      - TTS_URL=http://tts:8000
      - DATA_DIR=/data
    volumes:
      - ./data:/data
    ports:
      - "8000:8000"
    depends_on:
      - whisper
      - ollama

  whisper:
    build:
      context: .
      dockerfile: docker/whisper.Dockerfile
    image: ghcr.io/raolivei/ollie-whisper
    volumes:
      - ./data:/data

  ollama:
    build:
      context: .
      dockerfile: docker/ollama.Dockerfile
    image: ghcr.io/raolivei/ollie-ollama
    volumes:
      - ./data:/data
      - ollama_storage:/root/.ollama
    ports:
      - "11434:11434"

  ui:
    build:
      context: .
      dockerfile: docker/ui.Dockerfile
    image: ghcr.io/raolivei/ollie-ui
    environment:
      - OLLIE_API_URL=http://core:8000
    ports:
      - "8501:8501"
    depends_on:
      - core

  frontend:
    build:
      context: .
      dockerfile: docker/frontend.Dockerfile
    image: ghcr.io/raolivei/ollie-frontend
    ports:
      - "3000:80"
    depends_on:
      - core
      - whisper

volumes:
  ollama_storage:
