apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-tts
  labels:
    app: aeron
    component: tts
spec:
  replicas: 1
  selector:
    matchLabels:
      app: aeron
      component: tts
  template:
    metadata:
      labels:
        app: aeron
        component: tts
    spec:
      containers:
        - name: tts
          image: "{{ .Values.tts.image.repository }}:{{ .Values.tts.image.tag }}"
          imagePullPolicy: {{ .Values.tts.image.pullPolicy }}
          ports:
            - containerPort: 8000
          resources:
            {{- toYaml .Values.tts.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: tts
spec:
  selector:
    app: aeron
    component: tts
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000

