apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-ui
  labels:
    app: ollie
    component: ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ollie
      component: ui
  template:
    metadata:
      labels:
        app: ollie
        component: ui
    spec:
      containers:
        - name: ui
          image: "{{ .Values.ui.image.repository }}:{{ .Values.ui.image.tag }}"
          imagePullPolicy: {{ .Values.ui.image.pullPolicy }}
          ports:
            - containerPort: 8501
          env:
            - name: OLLIE_API_URL
              value: "http://core:8000"
          resources:
            {{- toYaml .Values.ui.resources | nindent 12 }}
---
apiVersion: v1
kind: Service
metadata:
  name: ui
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    app: ollie
    component: ui
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501
      {{- if eq .Values.ui.service.type "NodePort" }}
      nodePort: {{ .Values.ui.service.nodePort }}
      {{- end }}

