apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Release.Name }}-data-pvc
  labels:
    app: ollie
    component: storage
spec:
  accessModes:
    - {{ .Values.persistence.data.accessMode }}
  storageClassName: {{ .Values.global.storageClass }}
  resources:
    requests:
      storage: {{ .Values.persistence.data.size }}
